color0 #59413d
color1 #ffb4ab
color2 #ffb4a8
color3 #ffb4a8
color4 #f7bd59
color5 #ffb4a8
color6 #ffb4a8
color7 #f6ddd9
color8 #a88a85
color9 #ffb4ab
color10 #ffb4a8
color11 #ffb4a8
color12 #f7bd59
color13 #ffb4a8
color14 #ffb4a8
color15 #f6ddd9

cursor                #f6ddd9
cursor_text_color     #1d100e
background            #1d100e
foreground            #f6ddd9
selection_foreground  #e1bfb9
selection_background  #59413d
active_border_color   #ffb4a8
inactive_border_color #59413d
url_color             #ffb4a8

active_tab_foreground   #690001
active_tab_background   #ffb4a8
inactive_tab_foreground #e1bfb9
inactive_tab_background #59413d
cursor_trail_color      #e1bfb9
