color0 #574239
color1 #ffb4ab
color2 #ffb595
color3 #feb696
color4 #d6c959
color5 #ffb595
color6 #feb696
color7 #f4ded6
color8 #a68b80
color9 #ffb4ab
color10 #ffb595
color11 #feb696
color12 #d6c959
color13 #ffb595
color14 #feb696
color15 #f4ded6

cursor                #f4ded6
cursor_text_color     #1b110d
background            #1b110d
foreground            #f4ded6
selection_foreground  #dec0b4
selection_background  #574239
active_border_color   #ffb595
inactive_border_color #574239
url_color             #ffb595

active_tab_foreground   #581e00
active_tab_background   #ffb595
inactive_tab_foreground #dec0b4
inactive_tab_background #574239
cursor_trail_color      #dec0b4
